In [238]:
import numpy as np

## Check if two matrics of same size.

In [239]:
A = np.array([[1, 2, 3], [2, 3, 4]])
B = np.array([[1, 2, 4], [2, 3, 6]])
C = np.array([[5, 2, 9], [4, 3, 3]])
D = np.array([[1, 2], [2, 3]])

In [240]:
print(f"Is A and B Matrix are conformable for addition or subtraction? {A.shape == B.shape}")
print(f"Is B and C Matrix are conformable for addition or subtraction? {B.shape == D.shape}")
print(f"Is A and C Matrix are conformable for addition or subtraction? {A.shape == D.shape}")

Is A and B Matrix are of same dimension? True
Is B and C Matrix are of same dimension? False
Is A and C Matrix are of same dimension? False


## Row Vector

In [241]:
r = np.array([1, 2, 3])
print(r)
print(r.ndim)

[1 2 3]
1


## Column Vector

In [242]:
c = np.array([[4], [5], [6]])
print(c)
print(c.ndim)

[[4]
 [5]
 [6]]
2


### Convert row vector to column using newaxis

In [243]:
print(r[:, np.newaxis])

[[1]
 [2]
 [3]]


### Convert column vector to row using rehshape

In [244]:
print(r.reshape(r.shape))

[1 2 3]


## Alegbra of Matrics
## Addition

### Commutativity

In [245]:
try:
    np.add(A, D)
except ValueError:
    print(A.shape)
    print(D.shape)
    print("If two matrices A and B are of the same order, the two matrices are then conformable for addition or subtraction")

(2, 3)
(2, 2)
If two matrices A and B are of the same order, the two matrices are then conformable for addition or subtraction


In [246]:
if A.shape == B.shape:
    print("As shape of A and C are same. Addition is possible")
    print(np.add(A,B))

print("A+B = B+C")
np.array_equal(np.add(A,B), np.add(B,A))

As shape of A and C are same. Addition is possible
[[ 2  4  7]
 [ 4  6 10]]
A+B = B+C


True

### Associativity

In [247]:
print("A + (B + C) = (A + B) + C")
np.array_equal(np.add(A, np.add(B, C)),  np.add(np.add(A, B), C))

A + (B + C) = (A + B) + C


True

### Identity

In [248]:
print("A + 0 = A")
np.array_equal(np.add(A, np.zeros(A.shape)), A)

A + 0 = A


True

### Additive Inverse

In [249]:
print("A + (-A) = 0")
np.array_equal(np.add(A, -A), np.zeros(A.shape))

A + (-A) = 0


True

## With Scalar

### Commutativity

In [250]:
c = 2
_lhs = np.dot(c, np.add(A, B))
_rhs = np.add(np.dot(c, A), np.dot(c, B))
print("c(A+B) = cA + cB")
np.array_equal(_lhs, _rhs)

c(A+B) = cA + cB


True

### Associativity

In [251]:
k = 4
_lhs = np.dot((c+k), A)
_rhs = np.add(np.dot(c, A), np.dot(k, A))

print("(c+k)A = cA + kA")
np.array_equal(_lhs, _rhs)

(c+k)A = cA + kA


True

## Multiplication

We can multiple if no. of column in A is equal to rows in B

In [252]:
A = np.array([[1, 2, 3], [2, 3, 4]])
B = np.array([[1, 2], [2, 3], [4, 5]])

In [253]:
print(f"Is column of A {A.shape[1]} equal to row of B {B.shape[0]} ? {A.shape[1] == B.shape[0]}")
np.dot(A, B)

Is column of A 3 equal to row of B 3 ? True


array([[17, 23],
       [24, 33]])

In [254]:
try:
    print(f"Is column of C {C.shape[1]} equal to row of D {D.shape[0]} ? {C.shape[1] == D.shape[0]}")
    np.dot(C, D)
except ValueError as exception:
    print(str(exception))

Is column of C 3 equal to row of D 2 ? False
shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


### Matrix mulitplication is not Commutativity

In [255]:
print(f"Is AB == BA:")
np.array_equal(np.dot(A,B), np.dot(B,A))

Is AB == BA:


False

## Transpose

In [256]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 3], [2, 4]])
print("A tranpose")
A_t = A.transpose()
print(A_t)

A tranpose
[[1 3]
 [2 4]]


In [257]:
np.array_equal(A_t, B)

True

### Rules of Tranpose

#### 1. (A<sup>T</sup>)<sup>T</sup> = A

In [258]:
np.array_equal(np.transpose(A_t), A)

True

#### 2. (A+B)<sup>T</sup> = A<sup>T</sup> + B<sup>T</sup>

In [262]:
_lhs = np.transpose(np.add(A,B))
_rhs = np.add(A.transpose(), B.transpose())
np.array_equal(_lhs, _rhs)

True

#### 3. (cA)<sup>T</sup> = cA<sup>T</sup>

In [264]:
c = 3
_lhs = np.transpose(np.dot(c,A))
_rhs = np.dot(c, A.transpose())
np.array_equal(_lhs, _rhs)

True

#### 4. (AB)<sup>T</sup> = B<sup>T</sup>.A<sup>T</sup>

In [266]:
_lhs = np.transpose(np.dot(A,B))
_rhs = np.dot(B.transpose(), A.transpose())
np.array_equal(_lhs, _rhs)

True

#### 5. (AB)<sup>T</sup> ≠ A<sup>T</sup>.B<sup>T</sup>

In [269]:
_lhs = np.transpose(np.dot(A,B))
_rhs = np.dot(A.transpose(), B.transpose())
np.array_equal(_lhs, _rhs)

False

## Special Metrics (TODO)