In [149]:
import numpy as np

## Check if two matrics of same size.

In [150]:
A = np.array([[1, 2, 3], [2, 3, 4]])
B = np.array([[1, 2, 4], [2, 3, 6]])
C = np.array([[5, 2, 9], [4, 3, 3]])
D = np.array([[1, 2], [2, 3]])

In [151]:
print(f"Is A and B Matrix are of same dimension? {A.shape == B.shape}")
print(f"Is B and C Matrix are of same dimension? {B.shape == D.shape}")
print(f"Is A and C Matrix are of same dimension? {A.shape == D.shape}")

Is A and B Matrix are of same dimension? True
Is B and C Matrix are of same dimension? False
Is A and C Matrix are of same dimension? False


## Row Vector

In [152]:
r = np.array([1, 2, 3])
print(r)
print(r.ndim)

[1 2 3]
1


## Column Vector

In [153]:
c = np.array([[4], [5], [6]])
print(c)
print(c.ndim)

[[4]
 [5]
 [6]]
2


### Convert row vector to column using newaxis

In [154]:
print(r[:, np.newaxis])

[[1]
 [2]
 [3]]


### Convert row vector to column using rehshape

In [155]:
print(r.reshape(r.shape))

[1 2 3]


## Alegbra of Matrics
## Addition

### Commutativity

In [156]:
try:
    np.add(A, D)
except ValueError:
    print(A.shape)
    print(D.shape)
    print("If two matrices A and B are of the same order, the two matrices are then conformable for addition or subtraction")

(2, 3)
(2, 2)
If two matrices A and B are of the same order, the two matrices are then conformable for addition or subtraction


In [157]:
if A.shape == B.shape:
    print("As shape of A and C are same. Addition is possible")
    print(np.add(A,B))

print("A+B = B+C")
np.array_equal(np.add(A,B), np.add(B,A))

As shape of A and C are same. Addition is possible
[[ 2  4  7]
 [ 4  6 10]]
A+B = B+C


True

### Associativity

In [158]:
print("A + (B + C) = (A + B) + C")
np.array_equal(np.add(A, np.add(B, C)),  np.add(np.add(A, B), C))

A + (B + C) = (A + B) + C


True

### Identity

In [159]:
print("A + 0 = A")
np.array_equal(np.add(A, np.zeros(A.shape)), A)

A + 0 = A


True

### Additive Inverse

In [160]:
print("A + (-A) = 0")
np.array_equal(np.add(A, -A), np.zeros(A.shape))

A + (-A) = 0


True

## With Scalar

### Commutativity

In [168]:
c = 2
_lhs = np.dot(c, np.add(A, B))
_rhs = np.add(np.dot(c, A), np.dot(c, B))
print("c(A+B) = cA + cB")
np.array_equal(_lhs, _rhs)

c(A+B) = cA + cB


True

### Associativity

In [181]:
k = 4
_lhs = np.dot((c+k), A)
_rhs = np.add(np.dot(c, A), np.dot(k, A))

print("(c+k)A = cA + kA")
np.array_equal(_lhs, _rhs)

(c+k)A = cA + kA


True

## Multiplication

We can multiple if no. of column in A is equal to rows in B

In [182]:
A = np.array([[1, 2, 3], [2, 3, 4]])
B = np.array([[1, 2], [2, 3], [4, 5]])

In [189]:
print(f"Is column of A {A.shape[1]} equal to row of B {B.shape[0]} ? {A.shape[1] == B.shape[0]}")
np.dot(A, B)

Is column of A equal to row of B? True


array([[17, 23],
       [24, 33]])

In [191]:
try:
    print(f"Is column of C {C.shape[1]} equal to row of D {D.shape[0]} ? {C.shape[1] == D.shape[0]}")
    np.dot(C, D)
except ValueError as exception:
    print(str(exception))

Is column of C 3 equal to row of D 2 ? False
shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


### Matrix mulitplication is not Commutativity

In [195]:
print(f"Is AB == BA:")
np.array_equal(np.dot(A,B), np.dot(B,A))

Is AB == BA:


False