In [1]:
import numpy as np
from numpy import linalg as LA
import sympy

In [2]:
A = np.array([[2, 2, -1, 0], [-1, 1, 2, -3], [1, 1, -2, 0], [0, 0, 1, 1]])

In [3]:
A

array([[ 2,  2, -1,  0],
       [-1,  1,  2, -3],
       [ 1,  1, -2,  0],
       [ 0,  0,  1,  1]])

In [4]:
# Rank of A

In [6]:
LA.matrix_rank(A)

4

In [7]:
# RREF

In [8]:
print(sympy.Matrix(A).rref(normalize_last=True))

(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]), (0, 1, 2, 3))


In [9]:
# eigenvalues and eigenvectors

In [10]:
w, v = LA.eig(np.array([[1, -1], [1, 1]]))

In [12]:
w

array([1.+1.j, 1.-1.j])

In [13]:
v

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])